### ISSUE TITLE
help setting asymmetrical flex-box sizing.

### ISSUE THREAD

**Issue by heinskeys** [heinskeys/idm231-mba58#1]
@mrpaulphan Hi, so I am having literally the worst time trying to size these boxes. I wanted to ask if you had any advice on how I can set the sizes so things more closely match my intended vision. The way I currently have it set up is so that each section is separated into different div containers and I'm just using Flexbox to set up the columns, rows, shift the sizing etc. But, it's been very limiting in that is gotten harder to change the size of each individual box to fit my wireframes. I feel like there is definitely a much easier way to do this that doesn't require math/guessing because I definitely think the way I'm doing it would make it not work on anyone's screen but mine. 

Here is my wireframe for reference. (Also, hopefully, my code references correctly I've never made an issue request before.)

![Wireframe](https://github.com/heinskeys/idm231-mba58/assets/146353691/72716523-fe54-4653-b878-ef4c22358b74)

and here is how it's looking: 

![image](https://github.com/heinskeys/idm231-mba58/assets/146353691/794fc0d9-46a8-4205-9b05-52790add227b)

**Comment by heinskeys** [comment]
I'm not sure it has???? Here is the code regardless: 

```css
.zodiacProfile {
    display: flex;
    max-width: 100vw;
    max-height: 100vh;
}

.characterProfile,
.characterGif,
.characterTagline,
.characterVideo,
.characterZodiac,
.characterImage {
    border-style: solid;
    border-width: 0.1rem;
    border-color: black;
}


/* Sets the first set containing .characterProfile, .characterGif, .characterTagline, .characterVideo to be 65% of the viewport width. */
.setOne {
    display: flex;
    flex-direction: column;
    flex-basis: 65vw;
    height: 100vh;
}


/* Contains the character profile, gif and tagline. */
.rowOne{
    display: flex;
    flex-direction: row;
}


/* Contains the character gif and tagline */
.stackOne {
    display: flex;
    flex-direction: column;
}


/* Stacks the .characterZodiac and .characterImage atop each other into a column. Set's this column (Set 2) to be 35% of the viewport width. */
.stackTwo {
    display: flex;
    flex-direction: column;
    flex-basis: 35vw;
}


.characterProfile {
    flex: 0.7;
}
.characterGif {
    flex: 0.7;
}


.characterVideo {
    flex: .8;
}
.characterTagline {
    flex: 0.3;
}


.characterImage {
    display: flex;
    flex-grow: 2;
}
```
